### ISSUE TITLE
503 Server Error - Been up for around a month now!

### ISSUE THREAD

**Issue by sidsvash26** [SI3P/supWSD#8]
I'm using the python API and I get the following error when I parse any sentence to get the wordnet senses:
SupException: 503 Server Error: Service Unavailable for url: https://supwsd-supwsdweb.1d35.starter-us-east-1.openshiftapps.com/supwsdweb/v1/senses

This issue has been up for a month now. It used to resolve on its own in some time, but now I'm not able to parse anything at all.

**Comment by SI3P** [comment]
We are relocating all our web services to a new server. We will solve the problem once and for all within the next few days.

**Comment by sidsvash26** [comment]
Thanks for the update. Hope it is available soon. I am using it for a research project and it has been really helpful.

**Comment by SI3P** [comment]
It will take a couple of days.

**Comment by sidsvash26** [comment]
Any updates on this?

**Comment by SI3P** [comment]
Next week (sorry)
Yes, you can download the java code and all the models from github.

**Comment by sidsvash26** [comment]
I downloaded the java code and models from GitHub, but I'm struggling to get a probability distribution over WordNet senses for all the words in a given sentence. The description on the main GitHub page only mentions how to train and test on xml files. I'm able to use another system for now, but it would be good to compare my results across different systems. Sorry if I am troubling you too much.

**Comment by SI3P** [comment]
it.si3p.supwsd.modules.classification.scorer.Result.java
line 131:
@Override
public String toString() {
   return this.getID() + SEPARATOR + String.join(SEPARATOR, this.getAnswers());
}

**Comment by sidsvash26** [comment]
Thanks! But I think the link for downloading the jar file is missing in the readme file.

> Download the jar file from the site (link will shortly follow)

There's no link.

**Comment by sidsvash26** [comment]
Okay. So I managed to build the jar file by first cloning the repo and then running the following commands inside the repo directory:
```
mvn compile
mvn package
mvn install 
```
This created a directory named **target** which had the  **supwsd-toolkit-1.0.0.jar** file inside it. 

I copied the jar file back to the main repo directory and also put the models folder downloaded from the main github page - https://github.com/SI3P/supWSD (second model from OMSTI+SemCor)

Then I followed these steps:
I downloaded the test data of SemEval2015 from here - http://alt.qcri.org/semeval2015/task13/index.php?id=data-and-tools and copied the test data xml file and its key in the main repo folder and then ran the following:

`java -jar supwsd-toolkit-1.0.0.jar test supconfig.xml semeval-2015-task-13-en.xml semeval-2015-task-13-en-WSD.key`

I get the following error:
```
org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 26; cvc-enumeration-valid: Value '' is not facet-valid with respect to enumeration '[lexical, senseval, semeval7, semeval13, semeval15, plain]'. It must be a value from the enumeration.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3184)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3153)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3055)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2134)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:853)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at it.si3p.supwsd.config.Config.load(Config.java:70)
	at it.si3p.supwsd.SupWSD.test(SupWSD.java:103)
	at it.si3p.supwsd.App.main(App.java:27)
```

I followed the steps from the github page as much as I understood. Please let me know where I went wrong.

**Comment by sidsvash26** [comment]
I'm just trying to understand if there's a way to get the distribution of all word-senses evaluated on the given SemEval2015 file. I understood that part where you mentioned to override line 131 in 
it.si3p.supwsd.modules.classification.scorer.Result.java, but I'm unable to run the model on SemEval2015 data. Any help would be extremely appreciated.

**Comment by SI3P** [comment]
We are updating the site and all our services. We will soon publish the new models and release the latest version of the software.

**Comment by sidsvash26** [comment]
Thanks for the update. It'll be really helpful if you could point out what am I missing when I'm trying to test the model on semeval15. 

I realized that the `supconfig.xml` file didn't have any default values and hence I was getting the above errors, so I edited the `supconfig.xml` with relevant info and now it looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
	<working_directory>temp_results</working_directory>
	<parser mns="">semeval15</parser>
	<preprocessing>
		<!--<pipeline model=""></pipeline>-->	
		<splitter model="">stanford</splitter>
		<tokenizer model="">stanford</tokenizer>
		<tagger model="">stanford</tagger>
		<lemmatizer model="">stanford</lemmatizer>
		<dependency_parser model="">stanford</dependency_parser>
	</preprocessing>
	<extraction>
		<features>
			<pos_tags cutoff="5">true</pos_tags>
			<local_collocations cutoff="1">true</local_collocations>
			<surrounding_words cutoff="1" window="-1">true</surrounding_words>
			<word_embeddings strategy="EXP" window="2"
				vectors="/Users/sidvash/Dropbox/research/wsd/supWSD/embeddings_skip_wackyen_400d.bin"
				vocab="/Users/sidvash/Dropbox/research/wsd/supWSD/wackyEN.vocab.txt" cache="1">true</word_embeddings>
			<syntactic_relations>true</syntactic_relations>
		</features>
	</extraction>
	<classifier>libsvm</classifier>
	<writer>all</writer>
	<sense_inventory
		dict="/Users/sidvash/Dropbox/research/wsd/supWSD/wn3_dict/">wordnet</sense_inventory>
</supWSD>
```
Along with this, I also had to copy the `classes` and `dependency-jars` folders from the `target` folder to the main `supwsd` folder. 
After this, I ran the same following command again:
`java -jar supwsd-toolkit-1.0.0.jar test supconfig.xml semeval-2015-task-13-en.xml semeval-2015-task-13-en-WSD.key`

This time I get a different error as follows:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
precision : 0.000 ( 0 correct of 0 attempted )
recall : 0.000 ( 0 correct of 1113 in total )
f : 0.000
attempted : 0.000 ( 0 attempted of 1113 in total )
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "�(�:�А:{�{�V���9q�E:ףv9��]8�(l��c:����ǣ9��D���z��LY�3���="
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at it.si3p.supwsd.modules.extraction.Extractor.load(Extractor.java:55)
	at it.si3p.supwsd.modules.Analyzer.init(Analyzer.java:64)
	at it.si3p.supwsd.modules.Tester.init(Tester.java:72)
	at it.si3p.supwsd.modules.Analyzer.execute(Analyzer.java:53)
	at it.si3p.supwsd.SupWSD.test(SupWSD.java:125)
	at it.si3p.supwsd.App.main(App.java:27)
Caused by: java.lang.NumberFormatException: For input string: "�(�:�А:{�{�V���9q�E:ףv9��]8�(l��c:����ǣ9��D���z��LY�3���="
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at it.si3p.supwsd.modules.extraction.extractors.we.WEVirtualMemory.swap(WEVirtualMemory.java:103)
	at it.si3p.supwsd.modules.extraction.extractors.we.WEMemoryManagment.load(WEMemoryManagment.java:46)
	at it.si3p.supwsd.modules.extraction.extractors.WordEmbeddingsExtractor.load(WordEmbeddingsExtractor.java:95)
	at it.si3p.supwsd.modules.extraction.Extractor$1.call(Extractor.java:49)
	at it.si3p.supwsd.modules.extraction.Extractor$1.call(Extractor.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I'm not sure what am I missing here now.

**Comment by sidsvash26** [comment]
The above thing works fine if I turn-off the word-embeddings. There seemed to be something wrong with the embeddings file.

**Comment by SI3P** [comment]
We're back online: https://supwsd.net

I'll fix the problems with the toolkit in the coming days.
