### ISSUE TITLE
Training problem with parser errors

### ISSUE THREAD

**Issue by LuckyJLin** [SI3P/supWSD#9]
Sorry to bother you, there are some problems in my current research.
I attempt to train a new model with follow commands:
train supconfig.xml semcor.data.xml semcor.gold.key.txt

And my supconfig.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
	<working_directory>C:\Users\L\Desktop\WorkPlace\eclipse-workspace\supWSD\saveDir</working_directory>
	<parser mns="">semeval7</parser>
	<preprocessing>
		<!--<pipeline model=""></pipeline>-->	
		<splitter model=" .?!">simple</splitter>
		<tokenizer model="pre-trained_models\opennlp\en-token.bin">open_nlp</tokenizer>
		<tagger model="pre-trained_models\opennlp\en-pos-perceptron.bin">open_nlp</tagger>
		<lemmatizer model="">jwnl</lemmatizer>
		<dependency_parser model="">none</dependency_parser>
	</preprocessing>
	<extraction>
		<features>
			<pos_tags cutoff="0">true</pos_tags>
			<local_collocations cutoff="0">true</local_collocations>
			<surrounding_words cutoff="0" window="1" stopwords="">true</surrounding_words>
			<word_embeddings strategy="AVG" window="5" vectors="none" vocab="none" cache="0">false</word_embeddings>
			<syntactic_relations>false</syntactic_relations>
		</features>
	</extraction>
	<classifier>libsvm</classifier>
	<writer>all</writer>
	<sense_inventory dict="resources\wndictionary\wordnet">wordnet</sense_inventory>
</supWSD>
```

It will throw errors:
```
java.lang.IllegalArgumentException: No enum constant it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Tag.WF
	at java.lang.Enum.valueOf(Unknown Source)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Tag.valueOf(SemEval7Tag.java:1)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.startElement(SemEval7Handler.java:37)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at it.si3p.supwsd.modules.parser.XMLParser.parse(XMLParser.java:34)
	at it.si3p.supwsd.modules.Analyzer.execute(Analyzer.java:54)
	at it.si3p.supwsd.SupWSD.train(SupWSD.java:84)
	at it.si3p.supwsd.App.main(App.java:25)
```

My OS is Windows10, the IDE I used is "Eclipse Java Oxygen", the format of SemCor is from evaluation framework
of Raganato et al. (2017) which is cited in your paper.
Thanks for your watching and I'll appreciate pretty if you help me solve these problems ! ###

**Comment by LuckyJLin** [comment]
> Sorry to bother you, there are some problems in my current research.
> I attempt to train a new model with follow commands:
> train supconfig.xml semcor.data.xml semcor.gold.key.txt
> And my supconfig.xml:
> 
> 
> 	C:\Users\L\Desktop\WorkPlace\eclipse-workspace\supWSD\saveDir
> 	semeval7
> 	
> 			
> 		simple
> 		open_nlp
> 		open_nlp
> 		jwnl
> 		none
> 	
> 	
> 		
> 			true
> 			true
> 			true
> 			false
> 			false
> 		
> 	
> 	libsvm
> 	all
> 	wordnet
> 
> It will throw errors:
> java.lang.IllegalArgumentException: No enum constant it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Tag.WF
> My OS is Windows10, the IDE I used is "Eclipse Java Oxygen", the format of SemCor is from evaluation framework
> of Raganato et al. (2017) which is cited in your paper.
> Thanks for your watching and I'll appreciate pretty if you help me solve these problems !

**Comment by raganato** [comment]
the problem is the parser tag, with the semeval13 value should work 
<parser mns="">semeval13</parser>

**Comment by LuckyJLin** [comment]
I am so appreciate you solved this problem, and I could train models and saved them in disk, but there only are 183 trained models, the number should be 22436, it is too small. And there are some other exceptions occurred:

```
...
optimization finished, #iter = 1
nu = 1.0
obj = -2.0, rho = 0.0
nSV = 2, nBSV = 2
Total nSV = 117
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
org.xml.sax.SAXException
org.xml.sax.SAXException
java.lang.NullPointerException
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:147)
	at it.si3p.supwsd.modules.parser.xml.semeval13.SemEval13Handler.endElement(SemEval13Handler.java:60)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at it.si3p.supwsd.modules.parser.XMLParser.parse(XMLParser.java:34)
	at it.si3p.supwsd.modules.Analyzer.execute(Analyzer.java:54)
	at it.si3p.supwsd.SupWSD.train(SupWSD.java:84)
	at it.si3p.supwsd.App.main(App.java:25)
Caused by: org.xml.sax.SAXException
java.lang.NullPointerException
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:55)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:144)
	... 17 more
Caused by: java.lang.NullPointerException
	at it.si3p.supwsd.modules.classification.instances.AmbiguityTrain.cutoff(AmbiguityTrain.java:102)
	at it.si3p.supwsd.modules.Trainer.cutoff(Trainer.java:55)
	at it.si3p.supwsd.modules.Trainer.classify(Trainer.java:34)
	at it.si3p.supwsd.modules.Analyzer.annotationsReady(Analyzer.java:149)
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:52)
	... 18 more
```
I do not know where I am wrong. Thanks for your answer.

**Comment by LuckyJLin** [comment]
> the problem is the parser tag, with the semeval13 value should work
> <parser mns="">semeval13</parser>

I am so appreciated that you solved this problem, but after I ran the program again, I got some new problems. 
Firstly, the number of models generated from the program is only 183, which should be 22436. 
Secondly, there are some other exceptions occurred after I ran the program:
```
...
optimization finished, #iter = 1
nu = 1.0
obj = -2.0, rho = 0.0
nSV = 2, nBSV = 2
Total nSV = 117
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
org.xml.sax.SAXException
org.xml.sax.SAXException
java.lang.NullPointerException
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:147)
	at it.si3p.supwsd.modules.parser.xml.semeval13.SemEval13Handler.endElement(SemEval13Handler.java:60)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at it.si3p.supwsd.modules.parser.XMLParser.parse(XMLParser.java:34)
	at it.si3p.supwsd.modules.Analyzer.execute(Analyzer.java:54)
	at it.si3p.supwsd.SupWSD.train(SupWSD.java:84)
	at it.si3p.supwsd.App.main(App.java:25)
Caused by: org.xml.sax.SAXException
java.lang.NullPointerException
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:55)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:144)
	... 17 more
Caused by: java.lang.NullPointerException
	at it.si3p.supwsd.modules.classification.instances.AmbiguityTrain.cutoff(AmbiguityTrain.java:102)
	at it.si3p.supwsd.modules.Trainer.cutoff(Trainer.java:55)
	at it.si3p.supwsd.modules.Trainer.classify(Trainer.java:34)
	at it.si3p.supwsd.modules.Analyzer.annotationsReady(Analyzer.java:149)
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:52)
	... 18 more
```
What is wrong this time?

**Comment by LuckyJLin** [comment]
Now I have changed the supconfig.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
	<working_directory>savDir</working_directory>
	<parser mns="">semeval13</parser>
	<preprocessing>
		<!--<pipeline model=""></pipeline>-->	
		<splitter model="">stanford</splitter>
		<tokenizer model="">stanford</tokenizer>
		<tagger model="">stanford</tagger>
		<lemmatizer model="">stanford</lemmatizer>
		<dependency_parser model="">none</dependency_parser>
	</preprocessing>
	<extraction>
		<features>
			<pos_tags cutoff="0">true</pos_tags>
			<local_collocations cutoff="0">true</local_collocations>
			<surrounding_words cutoff="0" window="5">true</surrounding_words>
			<word_embeddings strategy="AVG" window="10"
				vectors="none"
				vocab="none" cache="0.5">false</word_embeddings>
			<syntactic_relations>false</syntactic_relations>
		</features>
	</extraction>
	<classifier>libsvm</classifier>
	<writer>all</writer>
	<sense_inventory
		dict="resources\wndictionary\wordnet">wordnet</sense_inventory>
</supWSD>
```
Something changed, the number of the generated models from 183 up to 6415, but the exceptions also changed:
```
...
optimization finished, #iter = 4
nu = 0.8888888888888888
obj = -8.0, rho = -1.0
nSV = 8, nBSV = 8
Total nSV = 8
WARNING: training data in only one class. See README for details.
Total nSV = 0
WARNING: training data in only one class. See README for details.
Total nSV = 0
org.xml.sax.SAXException: savDir\stat\con.VERB.stat.gz (句柄无效。)
org.xml.sax.SAXException: savDir\stat\con.VERB.stat.gz (句柄无效。)
java.io.FileNotFoundException: savDir\stat\con.VERB.stat.gz (句柄无效。)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:147)
	at it.si3p.supwsd.modules.parser.xml.semeval13.SemEval13Handler.endElement(SemEval13Handler.java:60)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at it.si3p.supwsd.modules.parser.XMLParser.parse(XMLParser.java:34)
	at it.si3p.supwsd.modules.Analyzer.execute(Analyzer.java:54)
	at it.si3p.supwsd.SupWSD.train(SupWSD.java:84)
	at it.si3p.supwsd.App.main(App.java:25)
Caused by: org.xml.sax.SAXException: savDir\stat\con.VERB.stat.gz (句柄无效。)
java.io.FileNotFoundException: savDir\stat\con.VERB.stat.gz (句柄无效。)
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:55)
	at it.si3p.supwsd.modules.parser.xml.semeval7.SemEval7Handler.notifyAnnotations(SemEval7Handler.java:144)
	... 17 more
Caused by: java.io.FileNotFoundException: savDir\stat\con.VERB.stat.gz (句柄无效。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at it.si3p.supwsd.modules.classification.Serializer.writeStatistic(Serializer.java:93)
	at it.si3p.supwsd.modules.classification.Learner.train(Learner.java:29)
	at it.si3p.supwsd.modules.Trainer.classify(Trainer.java:35)
	at it.si3p.supwsd.modules.Analyzer.annotationsReady(Analyzer.java:149)
	at it.si3p.supwsd.modules.parser.XMLParser.notifyAnnotations(XMLParser.java:52)
	... 18 more
```
I do not know what happend... can you help me ? Thank you very much!

**Comment by raganato** [comment]
i am unable to reproduce the error. I am training using semcor, your version of supconfig.xml, with the latest commit (10ffa5d), on an Ubuntu system.

**Comment by LuckyJLin** [comment]
I have solved this problem. The problem is the filename. I can't generate gzip file with filename "con.xx".
I surveyed the models you trained, and the name of model "con.VERB.model.gz" and "con.NOUN.model.gz" are changed to "_con.v.model.gz" and "_con.n.model.gz", so I changed them to "_con.VERB.model.gz" and "_con.NOUN.model.gz", too. Then it worked successfully! 
Thank you very much! 
Next, I will try to test models and learn more about this program. Probably I will inquiry more questions, wish you can continue to help me. So sorry to bother you.

**Comment by LuckyJLin** [comment]
Hello, there are two new problems. 
Firstly, when I test trained models, I don't know where to set the directory of trained models.  If I set it as the value of  ```working_directory``` in config.xml, it will generate new directories with nothing and cover original directories in which trained models are.
Secondly, I can't understand the usage of ```MNS``` in config.xml, where should I use it ?
So appreciative for your help!

**Comment by sidsvash26** [comment]
@LuckyJLin Did you figure out how to use the pre-trained models while testing?

I'm using the below config file, and tested on semeval13 and semeval15 evaluation datasets, but getting the WN 1st sense performance on both as per the Raganto's evaluation framework paper. Not sure how to use the pretrained models. 
```
<?xml version="1.0" encoding="UTF-8"?>
<supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
	<working_directory>temp_results</working_directory>
	<parser mns="">semeval13</parser>
	<preprocessing>
		<!--<pipeline model=""></pipeline>-->	
		<splitter model="">stanford</splitter>
		<tokenizer model="">stanford</tokenizer>
		<tagger model="">stanford</tagger>
		<lemmatizer model="">stanford</lemmatizer>
		<dependency_parser model="">stanford</dependency_parser>
	</preprocessing>
	<extraction>
		<features>
			<pos_tags cutoff="0">true</pos_tags>
			<local_collocations cutoff="0">true</local_collocations>
			<surrounding_words cutoff="0" window="-1">true</surrounding_words>
			<word_embeddings strategy="EXP" window="5"
				vectors="/Users/sidvash/Dropbox/research/wsd/supWSD/embeddings_skip_wackyen_400d.bin"
				vocab="/Users/sidvash/Dropbox/research/wsd/supWSD/wackyEN.vocab.txt" cache="1">false</word_embeddings>
			<syntactic_relations>true</syntactic_relations>
		</features>
	</extraction>
	<classifier>libsvm</classifier>
	<writer>all</writer>
	<sense_inventory
		dict="/Users/sidvash/Dropbox/research/wsd/supWSD/wn3_dict/">wordnet</sense_inventory>
</supWSD>
```

**Comment by LuckyJLin** [comment]
> @LuckyJLin Did you figure out how to use the pre-trained models while testing?
> I'm using the below config file, and tested on semeval13 and semeval15 evaluation datasets, but getting the WN 1st sense performance on both as per the Raganto's evaluation framework paper. Not sure how to use the pretrained models.
> <?xml version="1.0" encoding="UTF-8"?>
> <supWSD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supconfig.xsd">
> 	<working_directory>temp_results</working_directory>
> 	<parser mns="">semeval13</parser>
> 	<preprocessing>
> 			
> 		<splitter model="">stanford</splitter>
> 		<tokenizer model="">stanford</tokenizer>
> 		<tagger model="">stanford</tagger>
> 		<lemmatizer model="">stanford</lemmatizer>
> 		<dependency_parser model="">stanford</dependency_parser>
> 	</preprocessing>
> 	<extraction>
> 		<features>
> 			<pos_tags cutoff="0">true</pos_tags>
> 			<local_collocations cutoff="0">true</local_collocations>
> 			<surrounding_words cutoff="0" window="-1">true</surrounding_words>
> 			<word_embeddings strategy="EXP" window="5"
> 				vectors="/Users/sidvash/Dropbox/research/wsd/supWSD/embeddings_skip_wackyen_400d.bin"
> 				vocab="/Users/sidvash/Dropbox/research/wsd/supWSD/wackyEN.vocab.txt" cache="1">false</word_embeddings>
> 			<syntactic_relations>true</syntactic_relations>
> 		</features>
> 	</extraction>
> 	<classifier>libsvm</classifier>
> 	<writer>all</writer>
> 	<sense_inventory
> 		dict="/Users/sidvash/Dropbox/research/wsd/supWSD/wn3_dict/">wordnet</sense_inventory>
> </supWSD>

I think the problem is that the filename not the format need in program. I modified pre-trained model filename's pos-tag from lower to upper, such as from "aberration.n.stat.gz" to "aberration.NOUN.stat.gz". You can debug the program to watch its file handling and know details.

**Comment by SI3P** [comment]
try using the latest version of the Toolkit : https://supwsd.net/supwsd/downloads.jsp

Below are the results obtained using opennlp with the new models. 
In the coming weeks we will publish the models trained with the Stanford pipeline, with which the results of the paper were generated.

senseval2
precision : 0,713 ( 1626 correct of 2282 attempted )
recall : 0,713 ( 1626 correct of 2282 in total )
f : 0,713
attempted : 1,000 ( 2282 attempted of 2282 in total )

senseval3
precision : 0,692 ( 1280 correct of 1850 attempted )
recall : 0,692 ( 1280 correct of 1850 in total )
f : 0,692
attempted : 1,000 ( 1850 attempted of 1850 in total )

semeval2007
precision : 0,609 ( 277 correct of 455 attempted )
recall : 0,609 ( 277 correct of 455 in total )
f : 0,609
attempted : 1,000 ( 455 attempted of 455 in total )

semeval2013
precision : 0,653 ( 1074 correct of 1644 attempted )
recall : 0,653 ( 1074 correct of 1644 in total )
f : 0,653
attempted : 1,000 ( 1644 attempted of 1644 in total )

semeval2015
precision : 0,682 ( 697 correct of 1022 attempted )
recall : 0,682 ( 697 correct of 1022 in total )
f : 0,682
attempted : 1,000 ( 1022 attempted of 1022 in total )

**Comment by SI3P** [comment]
> 
> 
> Hello, there are two new problems.
> Firstly, when I test trained models, I don't know where to set the directory of trained models. If I set it as the value of `working_directory` in config.xml, it will generate new directories with nothing and cover original directories in which trained models are.

<working_directory>test-semcor</working_directory>
test-semcor
      models
            .NOUN.model
            .VERB.model
            ...
      stat
            .NOUN.stat
            .VERB.stat
            ...
      scores (output)

> Secondly, I can't understand the usage of `MNS` in config.xml, where should I use it ?
> So appreciative for your help!
MNS has been removed in the latest version of the Toolkit.

**Comment by LuckyJLin** [comment]
Thank you sir, so appreciate for your anwser! 
I'll try to implement it.
